---
- hosts: dev
  vars:
    - home_dir: /Users/alexbate/
    - applications: # these will be installed with brew cask idempotently
       - iterm2
       - intellij-idea-ce
       - java
       - spectacle
       - telegram

  tasks:
    - name: Check for installed apps(casks)
      shell: brew cask list | grep {{ item }}
      register: installed_applications
      with_items: "{{ applications }}"
      ignore_errors: true

    - name: Install apps with brew-cask   
      shell: brew cask install {{ item }}
      with_items: "{{ applications }}"
      when: item not in installed_applications.results|map(attribute='stdout')

    - name: install brew packages
      homebrew: update_homebrew=yes name={{ item }}
      with_items:
        - npm
        - nvm
        - vcsh
        - mr
        - maven
        - htop
        - wget
        - scala
        - sbt
        - tig
        - python
        - tmux
        - zsh
        - zsh-completions
        - tree
        - watch
        - postgresql
        - cowsay
      tags:
        - brew

      ######################### vundle ####################################

    - name: check if vundle repo has been cloned (this step isnt needed but i'm keeping it here for reference)
      stat: 
        path: ~/.vim/bundle/Vundle.vim
      register: vundle_exists 

    - name: checkout vundle
      git: 
        repo: git@github.com:VundleVim/Vundle.vim.git
        dest: ~/.vim/bundle/Vundle.vim

      ######################### mr ####################################

    - name: check if mr repo has been cloned
      command: cd ~
      command: vcsh mr rev-parse --verify master
      register: master
      failed_when: master.rc == 2

    - name: print response
      debug:
        msg: "Response code from check to see if mr exists in vcsh: {{ master.rc }} "

    - name: Clone mr with vcsh from polyglotpiglet
      command: vcsh clone 'git@github-personal:polyglotpiglet/mr.git'
      when: master.rc == 1 

    - name: mr update
      command: chdir=~ mr update
      ignore_errors: true

      ######################### scm_breeze ####################################

    - name: check if scm_breeze repo has been cloned
      stat:
        path: ~/.scm_breeze
      register: scm_breeze_exists

    - name: checkout scm_breeze
      git: 
        repo: git://github.com/scmbreeze/scm_breeze.git
        dest: ~/.scm_breeze

    - name: insall scm_breeze
      command: ~/.scm_breeze/install.sh && source ~/.bashrc
